name: verify

on: [push, pull_request]

jobs:
  portable:
    strategy:
      matrix:
        target: [wasm, wasm-gc, js]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hustcer/setup-moonbit@v1
      - run: moon check --target ${{ matrix.target }} --deny-warn
      - run: moon test --target ${{ matrix.target }} --deny-warn

  generated-interface:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: hustcer/setup-moonbit@v1
      - run: moon fmt --check
      - run: moon info
      - run: git diff --exit-code
      - run: moon run examples/check_move --target wasm-gc
